Issue #237: Display collateral balances
open-dollar/od-app pull request #243
Opened 2024-01-27 08:18 UTC by kai-thompson

Closes #237 

## Description
- Adds value prop to dropdown component
- Pass fetch data balance to new `value` prop in dropdown component
- Run `yarn format`

## Screenshots
#### Zero Balance
<img width="539" alt="image" src="https://github.com/open-dollar/od-app/assets/90171376/bd31009e-64ca-4192-8ec7-4d99b3cf6308">

#### Non-zero balance
TODO (im tired and sorta drunk sorry)

2024-01-27 08:34 UTC, kai-thompson commented
Do we want the text colour of the balance to be white or grey?

2024-01-29 17:17 UTC, pi0neerpat requested changes
- White is fine for text
- Can you format the number with commas? We have a helper function for that used in many places.
- Please run the linter in a separate PR

2024-01-29 17:55 UTC, pi0neerpat approved these changes

2024-01-29 22:17 UTC, merged

2024-01-29 22:23 UTC, jahabeebs reviewed
good for now, I think the ARB decimal issue will be fixed when we give it the proper # in the SDK but we may need to change how it's formatted