Issue #240: Display Pool Details
open-dollar/od-app pull request #257
Opened 2024-02-06 02:28 UTC by kai-thompson

Closes #240 

## Description
- gotta eat some food im hungry. gonna leave this in draft then maybe get back to this tonight - kai thompson 5/2/24

2024-02-07 19:10 UTC, jahabeebs requested changes

2024-02-07 19:10 UTC, jahabeebs commented on src/containers/Deposit/DepositDetails.tsx
> +    const formatDate = (dateStr: number): string => {
Might be good to move this function to the helper.ts file since we can reuse it

2024-02-07 19:10 UTC, jahabeebs commented on src/containers/Deposit/index.tsx
> +                            // TODO: Update values once user pool deposit data is available
As we discussed earlier you should be able to get these values from the SDK already. Feel free to use 0x8cc44a3Fe63E844f37CeE1C91f7b5bc4aD26639e as an address for testing

2024-02-07 19:10 UTC, jahabeebs commented on src/utils/deposits.ts
> +export const getParsedNitroPool = (pool: NitroPoolDetails): ParsedNitroPool => {
nice work!

2024-02-07 19:43 UTC, kai-thompson commented on src/containers/Deposit/DepositDetails.tsx
> +        }, 1000)
This is just for the countdown. I can make the refresh happen every 10 second though.

2024-02-07 20:53 UTC, jahabeebs commented on src/containers/Deposit/DepositDetails.tsx
> +        }, 1000)
ohh got it, let's leave it as you have it then

2024-02-08 00:28 UTC, jahabeebs approved these changes

2024-02-08 00:37 UTC, merged