chore: Fix and Enforce Formatting
open-dollar/od-app pull request #284
Opened 2024-03-19 01:39 UTC by kai-thompson

2024-03-19 17:45 UTC, jahabeebs requested changes
Thanks for cleaning the repo up 

- Let's change node-version in the ci-pr to 20 since we use this for the app itself. I don't mind having lint/formatting stuff in the CI as long as it doesn't block the PR from being merged (though maybe Pat would have a different opinion)
- An infinite loop was introduced somewhere in this PR that is preventing me from accessing any vaults in the testnet deployment (click into the Vercel testnet deployment in the PR and you'll see). Make sure you're able to enter into your vaults and deposit/withdraw without issues. If you need testnet tokens you can use the /claim command with your wallet address in the bot channel in our public Discord but we should test the basic functionality

Infinite loop

<img width="489" alt="Screenshot 2024-03-19 at 1 38 43 PM" src="https://github.com/open-dollar/od-app/assets/47253537/3f906f99-2eb0-4f03-9d6c-e1155ec2a03b">

Can't see vaults (sometimes it'll flicker the vault into view but very sporadically)

https://github.com/open-dollar/od-app/assets/47253537/66201a04-1ebf-4a61-8fc9-e4854e659059

2024-03-20 03:36 UTC, kai-thompson commented
> Thanks for cleaning the repo up
> 
> * Let's change node-version in the ci-pr to 20 since we use this for the app itself. I don't mind having lint/formatting stuff in the CI as long as it doesn't block the PR from being merged (though maybe Pat would have a different opinion)
> * An infinite loop was introduced somewhere in this PR that is preventing me from accessing any vaults in the testnet deployment (click into the Vercel testnet deployment in the PR and you'll see). Make sure you're able to enter into your vaults and deposit/withdraw without issues. If you need testnet tokens you can use the /claim command with your wallet address in the bot channel in our public Discord but we should test the basic functionality
> 
> Infinite loop
> 
> <img alt="Screenshot 2024-03-19 at 1 38 43 PM" width="489" src="https://private-user-images.githubusercontent.com/47253537/314168609-3f906f99-2eb0-4f03-9d6c-e1155ec2a03b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDYwNDMsIm5iZiI6MTcxMDkwNTc0MywicGF0aCI6Ii80NzI1MzUzNy8zMTQxNjg2MDktM2Y5MDZmOTktMmViMC00ZjAzLTlkNmMtZTExNTVlYzJhMDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYjExZDlhMjNiN2ZhZjE1Mjk0NDBkZTQ5YzM1MzIwOGE0ZmUyY2I3OTNjYWQxNzk4YjkwYjhiY2FlZDU4YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZnsN9GJ3wRevI0ny26SSCeuxvt126kT2UFoXaUyY1Oc">
> Can't see vaults (sometimes it'll flicker the vault into view but very sporadically)
> 
>  Screen.Recording.2024-03-19.at.1.37.57.PM.mov

Just removed all but one (not risky) useEffect dependency array changes!

2024-03-20 18:08 UTC, jahabeebs approved these changes

2024-03-20 20:40 UTC, pi0neerpat requested changes
Getting error
```js
Cannot read properties of undefined (reading 'charAt')
TypeError: Cannot read properties of undefined (reading 'charAt')
    at capitalizeName (http://localhost:3000/static/js/bundle.js:34642:37)
    at networkChecker (http://localhost:3000/static/js/bundle.js:24194:95)
    at http://localhost:3000/static/js/bundle.js:24223:5
    ```

2024-03-20 20:40 UTC, pi0neerpat commented on src/services/TransactionUpdater.tsx
> -import { toast } from 'react-toastify'
Lets leave this library in for now, since we might use it for bridged asset notifications

2024-03-23 23:11 UTC, kai-thompson commented
> import { toast } from 'react-toastify'



> Getting error
> 
> ```js
> Cannot read properties of undefined (reading 'charAt')
> TypeError: Cannot read properties of undefined (reading 'charAt')
>     at capitalizeName (http://localhost:3000/static/js/bundle.js:34642:37)
>     at networkChecker (http://localhost:3000/static/js/bundle.js:24194:95)
>     at http://localhost:3000/static/js/bundle.js:24223:5
>     ```
> ```

@pi0neerpat  Strange. What environment is this from? It seems to be working as expected locally for me. What're some steps I can take to replicate this?

2024-03-23 23:53 UTC, pi0neerpat approved these changes
The error was due to testing on Optimism, which only works on branch `optimism-hai`

2024-03-23 23:58 UTC, merged